apiVersion: v1
kind: Service
metadata:  
  name: node-port-backend-endabank
spec:
  type: NodePort
  selector:    
    app: backend-endabank
  ports:  
    - port: 8080
      targetPort: 8080
      nodePort: 30022
      protocol: TCP
      